[package]
name = "aptos-keygen"
version = "0.1.0"
description = "Command line utility to generate Ed25519 key pairs for testing"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
rand = "0.7.3"

aptos-crypto = { path = "../aptos-crypto" }
aptos-types = { path = "../../types" }

