[package]
name = "VeiledCoin"
version = "0.0.1"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
veiled_coin = "0x45"#"_"
confidential_asset = "0x56"
