[package]
name = "bonding_curve_launchpad"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
owner_addr = "0x922a028b0dbd8ff206074977ae4c5f9fb003ce384242b6253c67192cd2a45ee1"
resource_account = "0x756f17af1e6415dc4ba6dbc583d52adbc352b1cdd69f509739ada08c781400e6"
memecoin_creator_addr = "0x922a028b0dbd8ff206074977ae4c5f9fb003ce384242b6253c67192cd2a45ee1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
