[package]
name = "bonding_curve_launchpad"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
bonding_curve_launchpad = "_"
deployer = "0xcafe"
swap = "0xcafe"

[dev-addresses]
bonding_curve_launchpad = "0x650"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "bbf569abd260d94bc30fe96da297d2aecb193644"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.swap]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "bbf569abd260d94bc30fe96da297d2aecb193644"
subdir = "aptos-move/move-examples/swap"
