[package]
name = 'module_loading_star_dependencies'
version = '1.0.0'

[dependencies]
AptosStdlib = { local = "../../../../../aptos-move/framework/aptos-stdlib" }

[addresses]
publisher_address = "0xABCD"
