[package]
name = "aptos-intent"
description = "Generating Move Script from intent"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
hex = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
move-core-types = { workspace = true }
reqwest = { version = "*", features = ["blocking"] }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.42"

[dev-dependencies]
aptos-types = { workspace = true }
e2e-move-tests = { path = "../e2e-move-tests" }

[package.metadata.cargo-machete]
ignored = ["serde_bytes", "wasm-bindgen-futures"]
