[package]
name = "aptos-gas-calibration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aptos-abstract-gas-usage = { workspace = true }
aptos-gas-meter = { workspace = true }
aptos-gas-algebra = { workspace = true }
aptos-gas-schedule = { workspace = true }
aptos-vm-types = { workspace = true }
move-binary-format = { workspace = true }
anyhow = { workspace = true }
aptos-types = { workspace = true }
aptos-native-interface = { workspace = true }
aptos = { workspace = true }
aptos-cached-packages = { workspace = true }
aptos-framework = { workspace = true }
aptos-language-e2e-tests = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
move-bytecode-source-map = { workspace = true }
move-core-types = { workspace = true }
aptos-move-stdlib = { workspace = true }
move-vm-runtime = { workspace = true }
move-ir-compiler = { workspace = true }
move-vm-test-utils = { workspace = true }
nalgebra = { workspace = true }