[package]
name = "vm-validator"
version = "0.1.0"
description = "Aptos vm validator"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
fail.workspace = true

aptos-gas = { path = "../aptos-move/aptos-gas" }
aptos-state-view = { path = "../storage/state-view" }
aptos-types = { path = "../types" }
aptos-vm = { path = "../aptos-move/aptos-vm" }
scratchpad = { path = "../storage/scratchpad" }
storage-interface = { path = "../storage/storage-interface" }

[dev-dependencies]
rand = "0.7.3"

aptos-crypto = { path = "../crates/aptos-crypto", features = ["fuzzing"] }
aptos-temppath = { path = "../crates/aptos-temppath" }
aptos-types = { path = "../types", features = ["fuzzing"] }
aptos-vm = { path = "../aptos-move/aptos-vm" }
aptosdb = { path = "../storage/aptosdb", features = ["fuzzing"] }
cached-packages = { path = "../aptos-move/framework/cached-packages" }
executor-test-helpers = { path = "../execution/executor-test-helpers" }
move-deps = { path = "../aptos-move/move-deps", features = ["address32"] }
vm-genesis = { path = "../aptos-move/vm-genesis" }

[features]
default = []
failpoints = ["fail/failpoints"]
fuzzing = ["aptos-types/fuzzing", "aptos-crypto/fuzzing", "aptosdb/fuzzing"]
