[package]
name = "aptos-resource-viewer"
version = "0.1.0"
description = "Aptos resource viewer"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.57"

aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }

move-deps = { path = "../move-deps", features = ["address32"] }
