[package]
name = "aptos"
version = "0.2.1"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos tool for management of nodes and interacting with the blockchain"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"
build = "build.rs"

[dependencies]
async-trait = "0.1.53"
base64 = "0.13.0"
bcs = "0.1.3"
clap = "3.2.11"
clap_complete = "3.2.3"
hex = "0.4.3"
parse_duration = "2.1.1"
rand = "0.7.3"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = "1.0.137"
serde_json = "1.0.81"
serde_yaml = "0.8.24"
shadow-rs = "0.11.0"
tokio =  "1.18.2"
toml = "0.5.9"

aptos-cli-base = { path = "../aptos-cli-base" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../aptos-crypto", features = [] }
aptos-faucet = { path = "../aptos-faucet" }
aptos-genesis = { path = "../aptos-genesis" }
aptos-github-client = { path = "../../secure/storage/github" }
aptos-keygen = { path = "../aptos-keygen" }
aptos-logger = { path = "../aptos-logger" }
aptos-module-verifier = { path = "../../aptos-move/aptos-module-verifier" }
aptos-node = { path = "../../aptos-node" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
aptos-secure-storage = { path = "../../secure/storage" }
aptos-telemetry = { path = "../aptos-telemetry" }
aptos-temppath = { path = "../aptos-temppath" }
aptos-transaction-builder = { path = "../../sdk/transaction-builder" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }

cached-framework-packages =  { path = "../../aptos-move/framework/cached-packages" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32", "testing", "table-extension"] }

[build-dependencies]
shadow-rs = "0.11.0"
