[package]
name = "test_package"
version = "0.0.0"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }

[addresses]
source_addr = "_"

[dev-addresses]
source_addr = "0xcafe"