[package]
name = "storage-service-server"
version = "0.1.0"
description = "The Aptos storage service (server-side)"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
bcs.workspace = true
bytes.workspace = true
futures = "0.3.21"
lru = "0.7.5"
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.21.0", features = ["rt", "macros"], default-features = false }

aptos-config = { path = "../../../config" }
aptos-infallible = { path = "../../../crates/aptos-infallible" }
aptos-logger = { path = "../../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../../crates/aptos-metrics-core" }
aptos-time-service = { path = "../../../crates/aptos-time-service", features = ["async"] }
aptos-types = { path = "../../../types" }

bounded-executor = { path = "../../../crates/bounded-executor" }
channel = { path = "../../../crates/channel" }
network = { path = "../../../network" }
storage-interface = { path = "../../../storage/storage-interface" }
storage-service-types = { path = "../types" }

[dev-dependencies]
anyhow.workspace = true
claims = "0.7"
mockall = "0.11.0"
rand = "0.7.3"

aptos-bitvec = { path = "../../../crates/aptos-bitvec" }
aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-time-service = { path = "../../../crates/aptos-time-service", features = ["async", "testing"] }
aptos-types = { path = "../../../types" }
move-deps = { path = "../../../aptos-move/move-deps", features = ["address32"] }
storage-interface = { path = "../../../storage/storage-interface" }
