# :!:>manifest
[package]
name = 'UpgradeAndGovernExample'
version = '1.1.0'

[addresses]
upgrade_and_govern = '_'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
# <:!:manifest