[package]
name = "fa_bonding_curve_launchpad"
version = "1.0.0"
authors = []

[addresses]
bonding_curve_launchpad_addr = "_"
fa_obj_holder_addr = "_"
memecoin_creator_addr = "_"

[dev-addresses]
bonding_curve_launchpad_addr = "0x2832"
fa_obj_holder_addr = "0x81"
memecoin_creator_addr = "0x803"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
