[package]
name = "CommonAccount"
version = "1.0.0"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }

[addresses]
common_account = "_"

[dev-addresses]
common_account = "0xbeef"
