name: Rust Unit Tests
description: Runs all Rust unit tests
inputs:
  GIT_CREDENTIALS:
    description: "Optional credentials to pass to git. Useful if you need to pull private repos for dependencies"
    required: false
  BUILDKITE_ANALYTICS_TOKEN:
    description: "The Buildkite API token"
    required: true
  partition:
    description: "The partition number for the tests"

runs:
  using: composite
  steps:
    # The source code must be checkout out by the workflow that invokes this action.

    - uses: aptos-labs/aptos-core/.github/actions/rust-setup@main
      with:
        GIT_CREDENTIALS: ${{ inputs.GIT_CREDENTIALS }}

    # Install nextest
    - uses: taiki-e/install-action@v1.5.6
      with:
        tool: nextest
    
    # Install buildkite-test-collector
    - name: Install buildkite-test-collector
      run: cargo install buildkite-test-collector
      shell: bash

    # Run a postgres database
    - name: Run postgres database
      run: docker run --detach -p 5432:5432 cimg/postgres:14.2
      shell: bash

    - name: Download test artifacts
      uses: actions/download-artifact@v4
      with:
        name: nextest-archive

    # Run the rust unit tests
    - name: Run rust unit tests (partitioned)
      shell: bash
      run: cargo nextest run --archive-file /runner/_work/aptos-core/aptos-core/nextest-archive.tar.zst --partition hash:${{ inputs.partition }}/3  --retries 3 --no-fail-fast
      env:
        INDEXER_DATABASE_URL: postgresql://postgres@localhost/postgres
        RUST_MIN_STACK: "4297152"
        MVP_TEST_ON_CI: "true"
        SOLC_EXE: /home/runner/bin/solc
        Z3_EXE: /home/runner/bin/z3
        CVC5_EXE: /home/runner/bin/cvc5
        DOTNET_ROOT: /home/runner/.dotnet
        BOOGIE_EXE: /home/runner/.dotnet/tools/boogie
        BUILDKITE_ANALYTICS_TOKEN: ${{ inputs.BUILDKITE_ANALYTICS_TOKEN }}

    - name: Print size of targets directory and archive file
      run: du -sh /runner/_work/aptos-core/aptos-core/target /runner/_work/aptos-core/aptos-core/nextest-archive.tar.zst
      shell: bash
