[package]
name = "CoinExample"
version = "0.0.0"

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
coin_example = "_"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
AptosStdlib = { local = "../../framework/aptos-stdlib" }
MoveStdlib = { local = "../../framework/move-stdlib" }

[dev-addresses]
coin_example = "0xcafe"
