[package]
name = "NFTDAO"
version = "0.0.0"

[addresses]
dao_platform = "_"
aptos_framework = "0x1"

[dependencies]
AptosFramework = { local = "../../../framework/aptos-framework" }
AptosToken = { local = "../../../framework/aptos-token" }
