[package]
name = 'add-instr'
version = '1.0.0'
authors = []

[addresses]

[dependencies]
AptosFramework = { local = "../../../framework/aptos-framework" }
AptosStdlib = { local = "../../../framework/aptos-stdlib" }
MoveStdlib = { local = "../../../framework/move-stdlib" }
