[package]
name = "aptos-debugger"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "A tool to replay transactions on chain and to execute transactions locally with remote backend"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"

aptos-gas = { path = "../../aptos-move/aptos-gas" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }
aptos-validator-interface = { path = "../../aptos-move/aptos-validator-interface" }
aptos-resource-viewer = { path = "../../aptos-move/aptos-resource-viewer" }

move-binary-format = { workspace = true }
move-cli = { workspace = true }
move-compiler = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-test-utils = { workspace = true }
move-resource-viewer = { workspace = true }
move-core-types = { workspace = true }
move-table-extension = { workspace = true }
