[package]
name = "aptos-module-verifier"
version = "0.1.0"
description = "Aptos VM runtime"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
move-deps = { path = "../move-deps", features = ["address32"] }
