[package]
name = "aptos-validator-interface"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Defines interfaces between the aptos nodes and local move infrastructure"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
tokio = { version = "1.21.0", features = ["full"] }

aptos-api-types = { path = "../../api/types" }
aptos-config = { path = "../../config" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }

aptosdb = { path = "../../storage/aptosdb" }
move-binary-format = { workspace = true }
storage-interface = { path = "../../storage/storage-interface" }
