[package]
name = "aptos-validator-interface"
version = "0.1.0"
description = "Defines interfaces between the aptos nodes and local move infrastructure"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.57"

aptos-config = { path = "../../config" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }

aptosdb = { path = "../../storage/aptosdb" }
move-deps = { path = "../move-deps" }
storage-interface = { path = "../../storage/storage-interface" }
