[package]
name = "aptos-gas"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Gas metering for the Aptos blockchain"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
move-binary-format = { git = "https://github.com/move-language/move", rev = "9ad1087baa8940506483183717ba6a1e84e5a647" }
move-core-types = { git = "https://github.com/move-language/move", rev = "9ad1087baa8940506483183717ba6a1e84e5a647" }
move-stdlib = { git = "https://github.com/move-language/move", rev = "9ad1087baa8940506483183717ba6a1e84e5a647" }
move-vm-types = { git = "https://github.com/move-language/move", rev = "9ad1087baa8940506483183717ba6a1e84e5a647" }

framework = { path = "../framework" }

[features]
testing = ["move-stdlib/testing"]
