[package]
name = "aptos-gas"
version = "0.1.0"
description = "Gas metering for the Aptos blockchain"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
clap = { version = "3.1.17", features = ["derive"] }

move-binary-format = { git = "https://github.com/aptos-labs/move", rev = "77750b37bb3663d00a7c4058937fed42ceb3089e" }
move-core-types = { git = "https://github.com/aptos-labs/move", rev = "77750b37bb3663d00a7c4058937fed42ceb3089e" }
move-model = { git = "https://github.com/aptos-labs/move", rev = "77750b37bb3663d00a7c4058937fed42ceb3089e" }
move-stdlib = { git = "https://github.com/aptos-labs/move", rev = "77750b37bb3663d00a7c4058937fed42ceb3089e" }
move-table-extension = { git = "https://github.com/aptos-labs/move", rev = "77750b37bb3663d00a7c4058937fed42ceb3089e" }
move-vm-types = { git = "https://github.com/aptos-labs/move", rev = "77750b37bb3663d00a7c4058937fed42ceb3089e" }

aptos-global-constants = { path = "../../config/global-constants" }
aptos-types = { path = "../../types" }
framework = { path = "../framework" }
gas-algebra-ext = { path = "../gas-algebra-ext" }
package-builder = { path = "../package-builder" }

[dev-dependencies]
tempfile = "3.3.0"

[features]
testing = ["move-stdlib/testing", "aptos-global-constants/testing"]

[[bin]]
name = "aptos-gas-gen-update-proposal"
path = "src/bin/gen_proposal.rs"
