name: "Build aptos-debugger binary"
description: Build aptos-debugger binary

inputs:
  GIT_CREDENTIALS:
    description: "Optional credentials to pass to git"
    required: false
  GIT_SHA:
    required: true
    type: string
    description: The git SHA1 to test.

runs:
  using: composite
  steps:
    - name: assert GIT_SHA provided
      shell: bash
      run: |
        if [ -z "${{ inputs.GIT_SHA }}" ]; then
          echo "GIT_SHA is required"
          exit 1
        fi

    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.GIT_SHA }}

    - uses: aptos-labs/aptos-core/.github/actions/rust-setup@main
      with:
        GIT_CREDENTIALS: ${{ inputs.GIT_CREDENTIALS }}

    - name: Build aptos-debugger in release mode and strip
      shell: bash
      run: |
        cargo build --release -p aptos-debugger
        strip -s target/release/aptos-debugger

    # save explicitly, because rust-setup invokes rust-cache which cleans target/release up
    - uses: actions/cache/save@v4
      with:
        path: target/release/aptos-debugger
        key: aptos-debugger-${{ inputs.GIT_SHA }}
