[package]
name = "DefiExamples"
version = "1.0.0"

[addresses]
defi = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
