[package]
name = "aptos-parallel-executor"
version = "0.1.0"
description = "Aptos parallel transaction executor library"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
arc-swap = "1.5.0"
bcs.workspace = true
criterion = { version = "0.3.5", optional = true }
crossbeam = "0.8.1"
crossbeam-queue = "0.3.5"
dashmap = "5.2.0"
num_cpus = "1.13.1"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
rayon = "1.5.2"

aptos-aggregator = { path = "../aptos-aggregator" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }

mvhashmap = { path = "../mvhashmap" }

[dev-dependencies]
claims = "0.7"
criterion = "0.3.5"
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.7.3"

[features]
fuzzing = ["criterion", "proptest", "proptest-derive"]

[[bench]]
name = "scheduler_benches"
harness = false
required-features = ["fuzzing"]
