apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aptos-fullnode.fullname" . }}
  labels:
    {{- include "aptos-fullnode.labels" . | nindent 4 }}
data:
{{ (tpl (.Files.Glob "files/*.yaml").AsConfig .) | indent 2 }}

---

{{- if not .Values.chain.genesisConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aptos-fullnode.fullname" . }}-genesis
  labels:
    {{- include "aptos-fullnode.labels" . | nindent 4 }}
data:
  waypoint.txt: {{ .Files.Get (print "files/genesis/" .Values.chain.name "-waypoint.txt") }}
binaryData:
  genesis.blob: {{ .Files.Get (print "files/genesis/" .Values.chain.name "-genesis.blob") | b64enc }}
{{- end }}
