[package]
name = "HelloBlockchainExample"
version = "1.0.0"

[addresses]
hello_blockchain = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
