[package]
name = "peer-monitoring-service-server"
version = "0.1.0"
description = "The peer monitoring service (server-side)"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
bcs = "0.1.2"
bytes = "1.0.1"
futures = "0.3.12"
once_cell = "1.7.2"
serde = { version = "1.0.124", default-features = false }
thiserror = "1.0.24"
tokio = { version = "1.8.1", features = ["rt", "macros"], default-features = false }

aptos-config = { path = "../../../config" }
aptos-logger = { path = "../../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../../crates/aptos-metrics-core" }
aptos-types = { path = "../../../types" }

bounded-executor = { path = "../../../crates/bounded-executor" }
channel = { path = "../../../crates/channel" }
netcore = { path = "../../netcore" }
network = { path = "../../../network" }
peer-monitoring-service-types = { path = "../types" }
