[package]
name = "accumulator"
version = "0.1.0"
description = "Aptos merkle tree accumulator"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.57"
proptest = { version = "1.0.0", optional = true }

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-types = { path = "../../types" }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.7.3"

aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "aptos-crypto/fuzzing", "aptos-types/fuzzing"]
