[package]
name = "schemadb"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos schemadb"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
rocksdb = {git="https://github.com/rust-rocksdb/rust-rocksdb", rev="63240f6ea6865f344404815f64123b4ef59cc6c5", default-features=false, features=["lz4", "jemalloc"]}

aptos-config = { path = "../../config" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }

[dev-dependencies]
byteorder = "1.4.3"
proptest = "1.0.0"

aptos-temppath = { path = "../../crates/aptos-temppath" }

[features]
fuzzing = ["proptest"]
