[package]
name = "TokenObjectsMarketplace"
version = "0.0.0"

[addresses]
marketplace_contract = "_"

[dependencies]
AptosFramework = { local = "../../../framework/aptos-framework" }
AptosToken = { local = "../../../framework/aptos-token" }
AptosTokenObjects = { local = "../../../framework/aptos-token-objects" }
