validator:
  enableNetworkPolicy: false
  rust_log: debug,hyper=off
  # force enable the telemetry service to try to send telemetry
  force_enable_telemetry: true

fullnode:
  # at most one VFN per validator, depending on numFullnodeGroups
  groups:
  - name: fullnode
    replicas: 1
  rust_log: debug,hyper=off
  # force enable the telemetry service to try to send telemetry
  force_enable_telemetry: true

# Make all services internal NodePort and open all ports
# NodePort is required for ChaosMesh to function correctly: https://github.com/chaos-mesh/chaos-mesh/issues/3278#issuecomment-1134248492
service:
  validator:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: cloud.google.com/machine-family
                  operator: In
                  values:
                    - t2d
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/part-of
                  operator: In
                  values:
                    - aptos-node
            topologyKey: kubernetes.io/hostname
    image:
      repo: us-west1-docker.pkg.dev/aptos-global/aptos-internal/validator
    resources:
      limits:
        cpu: "46"
        memory: 64Gi
      requests:
        cpu: "46"
        memory: 64Gi
    storage:
      class: ssd
      size: 2500Gi
    external:
      type: "NodePort"
    internal:
      type: "NodePort"
    enableRestApi: true
    enableMetricsPort: true

  fullnode:
    external:
      type: "NodePort"
    internal:
      type: "NodePort"
    enableRestApi: true
    enableMetricsPort: true

# always assume we're spinning up a testnet and doing genesis rather than using the single validator test mode
loadTestGenesis: false
