[package]
name = "aptos-build-info"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
shadow-rs = "0.16.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
shadow-rs = "0.16.2"
