[package]
name = "TokenObjectsExample"
version = "1.0.0"

[addresses]
token_objects = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AptosTokenObjects = { local = "../../framework/aptos-token-objects" }
