[package]
name = "forge-cli"
version = "0.0.0"
description = "Aptos end to end test framework CLI"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
structopt = "0.3.21"
tokio = { version = "1.21.0", features = ["full"] }
url = "2.2.2"

aptos-global-constants = { path = "../../config/global-constants" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
cached-packages = { path = "../../aptos-move/framework/cached-packages" }
forge = { path = "../forge" }
framework = { path = "../../aptos-move/framework" }
serde_yaml = "0.8.24"
testcases = { path = "../testcases" }

[[bin]]
name = "forge"
path = "src/main.rs"
