[package]
name = "aptos-substreams"
version = "0.1.0"
description = "Substreams for Aptos Chain"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
edition = "2018"
repository = "https://github.com/aptos-labs/aptos-core"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.57"
prost = "0.10.1"
prost-types = "0.10.1"
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"
substreams = "0.0.12"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"