[package]
name = "aptos-genesis"
version = "0.1.0"
description = "A tool to manage genesis"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
rand = "0.7.3"
serde = { version = "1.0.137", features = ["rc"], default-features = false }
serde_yaml = "0.8.24"

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../aptos-crypto" }
aptos-keygen = { path = "../aptos-keygen" }
aptos-logger = { path = "../aptos-logger" }
aptos-state-view =  { path = "../../storage/state-view" }
aptos-temppath = { path = "../aptos-temppath" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }

aptosdb = { path = "../../storage/aptosdb" }
cached-packages = { path = "../../aptos-move/framework/cached-packages" }
executor = { path = "../../execution/executor" }
framework = { path = "../../aptos-move/framework" }
storage-interface = { path = "../../storage/storage-interface" }
vm-genesis = { path = "../../aptos-move/vm-genesis" }

[dev-dependencies]
aptos-config = { path = "../../config", features = ["fuzzing"] }

[features]
testing = []
fuzzing = ["aptos-config/fuzzing"]
