[package]
name = "transaction-emitter-lib"
version = "0.0.0"
description = "Library for Aptos transaction emitter"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
again.workspace = true
anyhow = { workspace = true, features = ["backtrace"] }
clap = "3.1.17"
futures = "0.3.21"
itertools = "0.10.3"
once_cell = "1.10.0"
rand = "0.7.3"
rand_core = "0.5.1"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.21.0", features = ["full"] }
url = { version = "2.2.2", features = ["serde"] }

aptos = { path = "../aptos" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../aptos-crypto" }
aptos-global-constants = { path = "../../config/global-constants" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-rest-client = { path = "../aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
