name: "Check Branch Commits"
description: |
  This action runs the branch commit checker, which helps to ensure that:
    1. All release branches are rolling forward appropriately, i.e., main -> devnet -> testnet -> mainnet.
    2. The public and private aptos-core repositories are in sync.

  To ensure the properties above, the branch commit checker verifies that:
    - In the public aptos-core repository:
      1. All commits in the `devnet`, `testnet` and `mainnet` branches, are in the `main` branch.
      2. All commits in the `testnet` branch are in `devnet` branch.
      3. All commits in the `mainnet` branch are in `testnet` branch.
    - Across the public and private aptos-core repositories:
      1. All commits in the private `aptos-release.*` branches are in the public `aptos-release.*` branches (and vice versa).
      2. All commits in the private `main` branch are in the public `main` branch (and vice versa).

inputs:
  TIMEOUT_MINUTES:
    description: "The number of minutes to wait for branch commit checking to finish."
    required: true

runs:
  using: composite
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        echo "${HOME}/bin/" >> $GITHUB_PATH # default INSTALL_DIR to path
    - name: Run branch commit checker
      shell: bash
      run: |
        source "$HOME/.cargo/env" # Required for allowing python access to cargo
        pip install -r ${{ github.action_path }}/requirements.txt
        timeout "${{ inputs.TIMEOUT_MINUTES }}m" python3 ${{ github.action_path }}/check_branch_commits.py
