[package]
name = "aptos-crypto-derive"
version = "0.0.3"
description = "Custom derives for `aptos-crypto`"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.38"
quote = "1.0.18"
syn = { version = "1.0.92", features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.57"
