[package]
name = "aptos-compression"
version = "0.1.0"
description = "A unified compression interface and implementation offered by Aptos"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
lz4 = "1.24.0"
once_cell = "1.10.0"
thiserror = "1.0.31"

aptos-logger = { path = "../aptos-logger" }
aptos-metrics-core = { path = "../aptos-metrics-core" }

[dev-dependencies]
bcs.workspace = true
serde = { version = "1.0.137", default-features = false }

aptos-crypto = { path = "../aptos-crypto" }
aptos-types = { path = "../../types" }
