[package]
name = "aptos-transactional-test-harness"
version = "0.1.0"
description = "Transactional testing framework for Move"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
clap = "3.1.8"
hex = "0.4.3"
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"

# Move dependencies
move-deps = { path = "../move-deps", features = ["address32"] }

# Aptos Move dependencies
aptos-api-types = { path = "../../api/types" }
aptos-gas = { path = "../aptos-gas" }
aptos-vm =  { path = "../aptos-vm" }
cached-packages =  { path = "../framework/cached-packages" }
framework =  { path = "../framework" }
language-e2e-tests = { path = "../e2e-tests" }
vm-genesis = { path = "../vm-genesis" }

# Other Aptos dependencies
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
storage-interface = { path = "../../storage/storage-interface" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
name = "tests"
harness = false
