[package]
name = "PostMintRevealExample"
version = "1.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token/", rev = "mainnet" }
DataStructure = { local = "../data_structures" }

[addresses]
# the source_addr and post_mint_reveal_nft here are for unit test purposes.
# in production, we should change them:
# - the source_addr should be the address of the account that creates the resource account
# - the post_mint_reveal_nft should be put as "_" if we publish the module by using the CLI command
# "aptos move create-resource-account-and-publish-package ..." because the CLI will automatically link
# the address to the package. If we are not using the CLI, the post_mint_reveal_nft should be the address
# of the resource account which is also the module publisher.
source_addr = "_"
post_mint_reveal_nft = "_"