[package]
name = "aptos-retrier"
version = "0.1.0"
description = "Generic retry and exponential backoff"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
tokio = { version = "1.21.0", features = ["time"] }

aptos-logger = { path = "../../crates/aptos-logger" }

