[package]
name = "Examples"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
AptosToken = { local = "../../framework/aptos-token" }

[addresses]
aptos_framework = "0x1"
# change it to `source_addr = "_" when calling from script / cli with named_addresses
source_addr = "0xcafe"
# change it to `admin_addr = "_" when calling from script / cli with named_addresses
admin_addr = "0xad"
