[package]
name = "crash-handler"
version = "0.1.0"
description = "Aptos crash handler"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
backtrace = "0.3.58"
serde = { version = "1.0.137", features = ["derive"] }
toml = "0.5.9"

aptos-logger = { path = "../../crates/aptos-logger" }

