[package]
name = "aptos-metrics-core"
version = "0.1.0"
description = "Aptos metrics shortcuts"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.57"
prometheus = { version = "0.13.0", default-features = false }

[dev-dependencies]
claims = "0.7"
