kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: default-buxybox-latency
spec:
  selector:
    labelSelectors:
      run: busybox
  mode: all
  action: delay
  delay:
    latency: "100ms"
  # from (the packets from target)
  # to (the packets to target)
  # both ( the packets from or to target).
  direction: to
  target:
    selector:
      namespaces:
        - {namespace}
      labelSelectors:
        app.kubernetes.io/name: validator
    mode: all
