[package]
name = "aptos-sdk"
version = "0.0.3"
description = "The Official Aptos SDK"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.57"
aptos-crypto = { path = "../crates/aptos-crypto" }
aptos-global-constants = { path = "../config/global-constants" }
aptos-rest-client = { path = "../crates/aptos-rest-client" }
aptos-types = { path = "../types" }
bcs = "0.1.3"
cached-packages = { path = "../aptos-move/framework/cached-packages" }
move-deps = { path = "../aptos-move/move-deps", features = ["address32"] }
rand_core = "0.5.1"
serde = { version = "1.0.137", features = ["derive"] }

# Used by the examples.
[dev-dependencies]
once_cell = "1.13.0"
rand = "0.7.3"
tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread"] }
url = "2.2.2"
