[package]
name = "storage-service-types"
version = "0.1.0"
description = "Common types offered by the Aptos storage service"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
bcs.workspace = true
num-traits = { version = "0.2.15", default-features = false }
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"

aptos-compression = { path = "../../../crates/aptos-compression" }
aptos-config = { path = "../../../config" }
aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-types = { path = "../../../types" }

[dev-dependencies]
claims = "0.7"
proptest = "1.0.0"
