[package]
name = "VeiledCoin"
version = "0.0.1"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
veiled_coin = "9ac6e327c67207e641be69940ab4abfe7a2920c969185ae2b8515e4fa45dce01"
