[package]
name = "fuzzer"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

[dependencies]
aptos-package-builder = { workspace = true }
aptos-framework = { workspace = true }
bcs = { workspace = true }
clap = "4.5.20"
move-binary-format = { workspace = true }
aptos-types = { workspace = true }
move-core-types = { workspace = true }