[package]
name = "fuzzer"
version = "0.1.0"
edition = "2021"
license = { workspace = true }

[dependencies]
aptos-framework = { workspace = true }
aptos-types = { workspace = true }
bcs = { workspace = true }
clap = "4.5.20"
move-core-types = { workspace = true }
