[package]
name = "Objects"
version = "0.0.1"

[dependencies]
AptosStdlib = { local = "../../framework/aptos-stdlib" }
AptosFramework = { local = "../../framework/aptos-framework" }

[addresses]
std = "0x1"
aptos_framework = "0x1"
