[package]
name = "stablecoin"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "../../../../../aptos-move/framework/aptos-framework" }

[addresses]
stablecoin = "0x100"
master_minter = "0x102"
denylister = "0x103"
metadata_updater = "0x104"

[dev-addresses]
stablecoin = "0x100"
master_minter = "0x102"
denylister = "0x103"
metadata_updater = "0x104"
