[package]
name = "proxy"
version = "0.1.0"
description = "Aptos proxy"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
ipnet = "2.5.0"


