[package]
name = "aptos-transaction-replay"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Replay transactions stored on chain"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
structopt = "0.3.21"
hex = "0.4.3"
aptos-workspace-hack = { path = "../../crates/aptos-workspace-hack" }
aptos-types = { path = "../../types" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-validator-interface = { path = "../aptos-validator-interface" }
aptosdb = { path = "../../storage/aptosdb" }
aptos-vm = { path = "../aptos-vm" }
move-binary-format = { git = "https://github.com/diem/move", rev = "da41c4d9fdf7aeaa4d645004d174fc23c328621c"}
move-cli = { git = "https://github.com/diem/move", rev = "da41c4d9fdf7aeaa4d645004d174fc23c328621c" }
move-vm-types = { git = "https://github.com/diem/move", rev = "da41c4d9fdf7aeaa4d645004d174fc23c328621c" }
move-core-types = { git = "https://github.com/diem/move", rev = "da41c4d9fdf7aeaa4d645004d174fc23c328621c", features=["address32"] }
move-vm-runtime = { git = "https://github.com/diem/move", rev = "da41c4d9fdf7aeaa4d645004d174fc23c328621c" }
move-vm-test-utils = { git = "https://github.com/diem/move", rev = "da41c4d9fdf7aeaa4d645004d174fc23c328621c" }
aptos-resource-viewer = { path = "../aptos-resource-viewer" }
framework =  { path = "../framework" }
move-compiler = { git = "https://github.com/diem/move", rev = "da41c4d9fdf7aeaa4d645004d174fc23c328621c" }
bcs = "0.1.2"
difference = "2.0.0"

[dev-dependencies]
vm-genesis = { path = "../vm-genesis" }
diem-framework-releases = { path = "../framework/DPN/releases" }
