name: "Docker buildx setup"
description: Sets up buildx for docker builds

runs:
  using: composite
  steps:
    - name: setup docker context for buildx
      id: buildx-context
      shell: bash
      run: docker context create builders

    - name: setup docker buildx
      uses: aptos-labs/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # pin v3.7.1
      with:
        endpoint: builders
        version: v0.17.1
        keep-state: true
        config-inline: |
          [worker.oci]
            gc = true
            gckeepstorage = 900000000000 # Use 900GB out of 1TB for builder storage
            [[worker.oci.gcpolicy]]
              keepBytes = 700000000000 # Use 700GB out of 900GB for cache storage
              keepDuration = 604800 # Keep cache for 7 days
              filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
            [[worker.oci.gcpolicy]]
              all = true
              keepBytes = 900000000000
