[package]
name = "DataStructure"
version = "0.0.1"

[dependencies]
AptosStdLib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "mainnet" }

[addresses]
std = "0x1"
