[package]
name = "aptos-writeset-generator"
version = "0.1.0"
description = "Generating writesets used for incident management"

# Workspace inherited keys
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
handlebars = "4.2.2"
serde = { version = "1.0.137", default-features = false }
tempfile = "3.3.0"

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive" }
aptos-gas = { path = "../aptos-gas" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../aptos-vm" }

cached-packages =  { path = "../framework/cached-packages" }
framework =  { path = "../framework" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32", "table-extension"] }
