name: CI

on:
  push:
    branches: 
      - rosetta-stable
  pull_request:

env:
  go_version: 1.17

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.setup_work.outputs.matrix}}
      workload: ${{steps.set_blks_per_chunk.outputs.blks_per_chunk}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - id: setup_work 
      env:
          START_INDEX: 100
          BLKS_PER_CHUNK: 20000
      run: echo "::set-output name=matrix::$(.github/workflows/script/setup.sh)"
    - id: set_blks_per_chunk
      run: echo "::set-output name=blks_per_chunk::500"

  rosetta-validation:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix: 
        range: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
    - run: |
          echo ${{ matrix.range }}
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

#     - run: nohup ./docker/rosetta/docker-build-rosetta.sh && \
# mkdir -p data && \
# cp config/src/config/test_data/public_full_node.yaml data/fullnode.yaml && \
# curl -o data/genesis.blob https://devnet.aptoslabs.com/genesis.blob && \
# curl -o data/waypoint.txt https://devnet.aptoslabs.com/waypoint.txt && \
# docker run -p 8082:8082 --rm -v $(pwd)/data:/opt/aptos/data aptos-core:rosetta-latest online --config /opt/aptos/data/fullnode.yaml > /dev/null 2>&1 &
    
    - name: run check:data on mainnet
      env:
        START_INDEX: ${{ matrix.range }}
        COUNT: ${{ needs.setup.outputs.workload }}
      run: .github/workflows/script/cli.sh
