name: Code Coverage
on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: docker run --detach -p 5432:5432 cimg/postgres:14.2
      # There's an issue with argument forwarding in `llvm-cov` that requires us to place `nextest` at the end.
      - run: cargo llvm-cov nextest
        env:
          INDEXER_DATABASE_URL: postgresql://postgres@localhost/postgres
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: false
