name: "execution-performance"
on:
  pull_request:

jobs:
  execution-performance:
    uses: ./.github/workflows/workflow-run-execution-performance.yaml
    secrets: inherit
    with:
      GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      RUNNER_NAME: executor-benchmark-runner

  spot-runner-execution-performance:
    uses: ./.github/workflows/workflow-run-execution-performance.yaml
    secrets: inherit
    with:
      GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
      RUNNER_NAME: spot-runner