name: Trigger Processor Tests on JSON Change

on:
  workflow_dispatch:
  pull_request:  # Trigger on PR-level events
    branches:
      - main

# Grant the required permissions to request the ID token
permissions:
  id-token: write  # This is required for GCP authentication
  contents: read   # Ensure the workflow has access to repository contents


jobs:
  dispatch_event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run CLI to Generate JSON Files
        run: |
               cd ecosystem/indexer-grpc/indexer-transaction-generator
          #          cargo run -- --testing-folder ./example_tests --output-folder ../indexer-test-transactions/json_transactions
               cargo run -- --config ./example.yaml --output-folder ../indexer-test-transactions/json_transactions

        working-directory: rust

      - name: Compare JSON Files
        run: |
          diff -qr generated_jsons/ indexer-test-transactions/json_transactions/
        continue-on-error: true
        id: diff_check

      - name: Dispatch Event to Processor Repo
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          TOKEN: '${{ steps.secrets.outputs.token }}'
          repository: 'aptos-labs/aptos-indexer-processors'
          event-type: 'json-change-detected'
          client-payload: '{"commit_hash": "${{ github.sha }}"}'
