name: "Keyless Circuit Daily Test"
on:
  # Allow us to manually run this specific workflow without a PR
  workflow_dispatch:
  schedule:
    - cron: "12 12 * * *" # at 12:12 UTC every day
  pull_request:
    paths:
      - ".github/workflows/keyless-circuit-daily-test.yaml"

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  run-all-circuit-tests:
    runs-on: high-perf-docker
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get all the history because cargo xtest --change-since origin/main requires it.
      - uses: ./.github/actions/keyless-circuit-setup
      - run: cargo test -p aptos-keyless-circuit-tests
