name: "Lint+Test"
on:
  pull_request:
  push:
    branches:
      - main
      - devnet

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  rust-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-setup
      - uses: pre-commit/action@v3.0.0
      - run: cargo install cargo-sort
      - run: scripts/rust_lint.sh --check

  rust-doc-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get all the history because cargo xtest --change-since origin/main requires it.
      - uses: ./.github/actions/rust-setup
      - run: cargo test --doc --workspace --exclude aptos-node-checker

  rust-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get all the history because cargo xtest --change-since origin/main requires it.
      - uses: ./.github/actions/rust-setup
      - run: docker run --detach -p 5432:5432 cimg/postgres:14.2
      - uses: taiki-e/install-action@v1.5.6
        with:
          tool: nextest
      - run: cargo nextest run --profile ci --workspace --exclude smoke-test --exclude backup-cli --exclude testcases --retries 3 --no-fail-fast
        env:
          INDEXER_DATABASE_URL: postgresql://postgres@localhost/postgres

  rust-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-setup
      - run: docker run --detach -p 5432:5432 cimg/postgres:14.2
      - uses: taiki-e/install-action@v1.5.6
        with:
          tool: nextest
      # prebuild node binary, so that tests don't start before node is built.
      # --test-threads is intentionally set to reduce resource contention in ci jobs. Increasing this, increases job failures and retries.
      - run: cargo build --bin=aptos-node --features=failpoints --release && LOCAL_SWARM_NODE_RELEASE=1 cargo nextest run --release --profile ci --package smoke-test --test-threads 6 --retries 3
        env:
          INDEXER_DATABASE_URL: postgresql://postgres@localhost/postgres

      - name: Upload smoke test logs for failures
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: failed-smoke-test-logs
          # Retain all smoke test data except for the db (which may be large).
          path: |
            /tmp/.tmp*
            !/tmp/.tmp*/**/db/
          retention-days: 1
