name: Run continuous pre release testing

permissions:
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - pre-release-continuous-test
  schedule:
    # Run hourly
    - cron: "0 * * * *"

jobs:
  run-forge:
    uses: ./.github/workflows/run-forge.yaml
    secrets: inherit
    with:
      GIT_SHA: ${{ github.sha }}
      merge_or_canary: canary
      FORGE_NAMESPACE: continuous
  debug-forge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.GIT_SHA }}
      - name:
        run: echo ${{ toJSON(github) }}
      - name: Set kubectl context
        run: aws eks update-kubeconfig --name $FORGE_CLUSTER_NAME
        env:
          FORGE_CLUSTER_NAME: ${{ secrets.FORGE_CLUSTER_NAME}}
