name: Semgrep

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/**'

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
           SEMGREP_RULES: >-
             ./.github/linters/semgrep/pull-request-target-code-checkout.yaml
